/*-----------------------------------------------------------------------------
 * EcFlags.cpp
 * Author                   Yang Luo , luoyang@sia.cn
 * Last Modification Date   2023.04.04 18:00
 *---------------------------------------------------------------------------*/
#include <regex>
#include "ecat_flags.h"


//! @brief Ec-Master ID (Multi-Master can be used)
DEFINE_int32(id, 0, "Ec-Master ID (Multi-Master can be used)");

//! @brief Bus cycle time in usec. Default is 1000
DEFINE_int32(cycle, 1000, "Bus cycle time in μsec. Specifies the bus cycle time. Defaults to 1000μs (1ms).");

//! @brief Verbosity level
DEFINE_int32(verbose, 3, "Verbosity level: 0=off (default), 1..n=more messages. The verbosity level specifies how much console output messages will be generated by the demo application. A high verbosity level leads to more messages.");

//! @brief Which CPU the Ec-Master use
DEFINE_int32(cpuidx, 0, "0 = first CPU, 1 = second, .... The CPU affinity specifies which CPU the demo application ought to use.");

//! @brief Measurement in us for all EtherCAT jobs
DEFINE_bool(perf, true, "Enable max. and average time measurement in μs for all EtherCAT jobs (e.g. ProcessAllRxFrames). Level: 0 = off, 1 (default) = min/avg/max, 2 = additional histogram");

//! @brief DC mode
DEFINE_int32(dcmmode, 1, "Set DCM mode. 0 = off, 1 = busshift, 2 = mastershift, 3 = linklayerrefclock, 4 = masterrefclock, 5 = dcx");

DEFINE_string(instance, "enp6s0", "Device instance 1=first, 2=second. The device instance specifies which network card is used by the demo application. The default is the first network card. ");

DEFINE_string(state, "op", "The request state of EtherCAT slaves. value can be init/preop/safeop/op The default is op. ");